# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '''
$directory$git_branch$ruby$nodejs
$git_status$character
'''

[docker_context]
disabled = true

[git_branch]
format = '[$symbol$branch]($style) '

[git_status]
format = "[($ahead_behind$stashed)]($style) "

[ruby]
symbol = "󰴭"
format = '[$symbol($version)]($style) '

[nodejs]
symbol = "󰎙"
format = '[$symbol($version)]($style) '
style = "green"
