# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '''
$directory$ruby$nodejs
$git_branch$git_status$character
'''

# Something like this might be cool, but this isn't.
# format = '''
# [┌───────────────────>](bold green)
# [│](bold green)$directory$ruby$nodejs
# [└─>](bold green)$git_branch$git_status$character
# '''

[docker_context]
disabled = true

[git_branch]
format = '[$symbol$branch]($style) '

[git_status]
format = "[($ahead_behind$stashed)]($style) "

[ruby]
symbol = "󰴭"
format = '[$symbol ($version)]($style) '
version_format = '${raw}'

[nodejs]
symbol = "󰎙"
format = '[$symbol ($version)]($style) '
style = "green"
version_format = '${raw} '
